language: node_js
node_js:
  - "8"

script :
  - "npm run build"

branches:
  only:
  - master

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   local_dir: build
#   on:
#     branch: master
        

deploy:
  provider: npm
  email: heifade@126.com
  api_key: f8580c88-7362-4336-a6a7-0c77f728761d
  on:
    tags: false
    repo: heifade/djd-test5





